version: "3.9"
services:
  haproxy:
    network_mode: host
    ports:
      - 8080:8080
    image: haproxy:2.7
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - ./scripts/:/usr/local/etc/haproxy/scripts/
  nginx:
    ports:
      - 81:80
    image: "nginx:latest"
    volumes:
      - ./nginx:/usr/share/nginx/html
